#!/usr/bin/perl -wl

use strict;
use Net::Twitter;
use Scalar::Util 'blessed';

#get credentials

my $user = $ENV{twitbot_user};
my $pass = $ENV{twitbot_pass};
print "user: $user pass: $pass"; 

my $nt = Net::Twitter->new(
    traits   => [qw/OAuth API::REST/],
    username => $user,
    password => $pass,
    consumer_key => "WccGI1q18LpM4EZ1yHC9Gw",
    consumer_secret => "LWhnR6UItmKDed6iOq0dSEmHnb3TSDbhOOcORKoO1A"
    );

my $result = $nt->update('changing client! ' . localtime());
